const express = require('express');
const apiRouter = require('./routes/api');

// Auto-generated by scripts/bundle-public.js — inlined to avoid pkg path issues
const staticFiles = require('./static');

function createServer() {
  const app = express();

  app.use(express.json({ limit: '3mb' }));
  app.use(express.urlencoded({ extended: true, limit: '3mb' }));

  app.use('/api', apiRouter);

  app.get('/', (_req, res) => {
    const file = staticFiles['index.html'];
    if (!file) return res.status(404).send('index.html not found');
    res.setHeader('Content-Type', file.mime);
    return res.send(file.data);
  });

  app.get(/^\/.+/, (req, res, next) => {
    const name = req.path.slice(1);
    const file = staticFiles[name];
    if (!file) return next();
    res.setHeader('Content-Type', file.mime);
    return res.send(file.data);
  });

  return app;
}

module.exports = { createServer };
